Description: YAML Configuration file with dummy authentication parameters
ProductNames:
  - teams
  # - exo
  # - defender
  - aad
  # - sharepoint
M365Environment: commercial
Organization: abcdef.organization.com
AppID: 0123456789abcdef01234566789abcde
CertificateThumbprint: fedcba9876543210fedcba9876543210fedcba98
