Description: |
  SCuBAGear YAML Configuration file with custom variables
  This configuration shows a standard SCuBAGear set of parameters to run
  but also includes examples of custom variables for use and reference
  in Rego policy assessments against the Defender baseline.  Using
  policy-specific variables to define sensitive users, groups, and domains.
  Defender preset security policies will then be assessed to ensure sensitive
  accounts, as specified by matching policy assignment filters, are included according to the Defender baseline policy.
  Any account or domain designated as sensitive should be carefully
  considered and documented as part of an organization's cybersecurity risk
  management program process and practices.
  This example includes the following design choices for illustrative purposes:
  - Use of Pascal case convention for variable names
  - Defines a namespace for values to be used across baselines/products (i.e., GlobalVars)
  - Per product namespace for values related to that specific product (i.e., Defender, SharePoint)
  - Namespace for each policy item within a product for variables related only to one policy item (i.e., Defender.MS.DEFENDER.1.4v1)
  - Use of YAML anchors and aliases following DRY (Don't Repeat Yourself) principle for repeated values and sections
ProductNames:
- defender
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
GlobalVars:  # For cross product variables
  AllProductVar: value_example
Defender:
  MS.DEFENDER.1.4v1: &CommonSensitiveAccountFilter
    # Defines sensitive accounts filters used to select accounts to assign to
    # the Strict Preset Security Policy for Exchange Online Protections
    # Values for each key should match those shown in the 'Apply Exchange 
    # Online Protection' section of the manage protection settings dialog.
    SensitiveAccounts:
      IncludedUsers:
        - johndoe@random.example.com
      IncludedGroups:
        - Dune
      IncludedDomains:
        - random.mail.example.com
      ExcludedUsers:
        -
      ExcludedGroups:
        -
      ExcludedDomains:
        -
  MS.DEFENDER.1.5v1: *CommonSensitiveAccountFilter
    # Defines sensitive accounts filters used to select accounts to assign to
    # the Strict Preset Security Policy for Defender for Office 365.
    # Values for each key should match those shown in the 'Apply Defender for 
    # Office 365 protection' section of the manage protection settings dialog.
    # Note:  This example uses a YAML alias to re-use MS.DEFENDER.1.4v1 values
  MS.DEFENDER.2.1v1 : &UserImpersonationProtection
    # Defines sensitive user accounts by display name and email address in
    # the Strict and Standard Preset Security Policies impersonation 
    # protection section.
    # Each value should be a string in the form of the display name and 
    # email address separated by a semicolon.
      SensitiveUsers:
        - John Doe;jdoe@someemail.com
  MS.DEFENDER.2.2v1 : &AgencyDomainImpersonationProtection
    # Defines a list of agency domain names that should be specified
    # in the Strict and Standard Preset Security Policies impersonation
    # protection section.
      AgencyDomains:
        - random.mail.example.com
  MS.DEFENDER.2.3v1 : &PartnerDomainImpersonationProtection
    # Defines a list of frequent partner domain names that should be
    # specified in the Strict and Standard Preset Security Policies
    # impersonation protection section.
      PartnerDomains:
        - random.mail.example.com