Description: YAML Configuration file for unit test in SCuBA
ProductNames:
  - teams
  - exo
  - defender
  - entraid
  - sharepoint
  - powerplatform
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
AnObject:
  name: MyObjectName
