Description: |
  SCuBAGear YAML Configuration file with custom variables
  This configuration shows a standard SCuBAGear set of parameters to run
  but also includes an example of a custom variable for use and reference
  in Rego policy assessments against the EXO baseline.  Specifically, using
  policy specific variables to allow automatic forwarding to specific domain
  names.
  This example includes the following design choices for illustrative purposes:
  - Use of Pascal case convention for varible names
  - Per product namespace for values related to that specific product (i.e., Exo)
  - Namespace for each policy item within a product for variables related only to one policy item (i.e., Exo.1.1v2)
ProductNames:
  - exo
M365Environment: commercial
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
Exo:
  # All EXO specific variables go here
  MS.EXO.1.1v2:
    AllowedForwardingDomains:
      - example1.com
      - example2.com