Description: |
  YAML Configuration file for unit test in SCuBA
  This config file does not include any per product namespace variables
  For more specific per product config variables please refer to the sample config associated with that product
  This example includes the following design choices for illustrative purposes:
  - Use of Pascal case convention for variable names
  - Example use of a custom variable
ProductNames:
  - teams
  - exo
  - defender
  - aad
  - sharepoint
  - onedrive
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutActionPlanFileName: ActionPlan
OutReportName: BaselineReports
AnObject:
  name: MyObjectName
