Description: YAML Configuration file for unit test of ConfigFilePath overrides
ProductNames:
  - teams
M365Environment: commercial
OPAPath: .
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: ScubaReports
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
OutJsonFileName: ScubaResults

# Test parameters for credentials
Organization: sub.domain.com
AppID: 12345678-1234-1234-1234-123456789012
CertificateThumbprint: 1234567890ABCDEF1234567890ABCDEF12345678
