Description: YAML Configuration file for unit test in SCuBA
ProductNames:
- teams
- exo
- defender
- aad
- sharepoint
- onedrive
M365Environment: commercial
OPAPath: C:\Program Files\OPA\opa_windows_amd64.exe
LogIn: true
DisconnectOnExit: false
OutPath: .
OutFolderName: M365BaselineConformance
OutProviderFileName: ProviderSettingsExport
OutRegoFileName: TestResults
OutReportName: BaselineReports
AnObject:
  name: MyObjectName
