# Run functional tests for Entra ID

name: Function Test Entra ID

# This is a reusable workflow called by the pipeline.
on:
  workflow_call:
    inputs:
      EmailOnFailure:
        description: "The email address to send if workflow fails."
        required: true
        type: string
      GitHubEventSchedule:
        description: "A type of GitHub event"
        required: true
        type: string
      GitHubEventName:
        description: "The name of a GitHub event"
        required: true
        type: string
    secrets:
      PfxBase64:
        required: true
      PfxPassword:
        required: true
      TestParams:
        required: true
      TestParamsDev:
        required: true
      NotifierUsername:
        required: true
      NotifierPassword:
        required: true
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  Ent_Tenant1:
    name: Ent_Tenant1
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: Entra_Tenant1
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant1
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant1
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant1 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
  Ent_Tenant1_G5:
    name: Ent_Tenant1_G5
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    if: ${{ always() }}
    needs:
      - Ent_Tenant1
    concurrency:
      group: Entra_Tenant1
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant1_G5
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant1_G5
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant1_G5 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
  Ent_Tenant2:
    name: Ent_Tenant2
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: Entra_Tenant2
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant2
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant2
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant2 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
  Ent_Tenant2_G3:
    name: Ent_Tenant2_G3
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    if: ${{ always() }}
    needs:
      - Ent_Tenant2
    concurrency:
      group: Entra_Tenant2
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant2_G3
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant2_G3
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant2_G3 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
  Ent_Tenant3:
    name: Ent_Tenant3
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: Entra_Tenant3
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant3
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant3
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant3 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
  Ent_Tenant3_G5:
    name: Ent_Tenant3_G5
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    if: ${{ always() }}
    needs:
      - Ent_Tenant3
    concurrency:
      group: Entra_Tenant3
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant3_G5
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant3_G5
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant3_G5 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
  Ent_Tenant6:
    name: Ent_Tenant6
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    concurrency:
      group: Entra_Tenant6
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant6
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant6
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant6 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
  Ent_Tenant6_G5:
    name: Ent_Tenant6_G5
    runs-on: windows-latest
    environment: Development
    permissions:
      id-token: write
      contents: write
    if: ${{ always() }}
    needs:
      - Ent_Tenant6
    concurrency:
      group: Entra_Tenant6
      cancel-in-progress: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          path: repo
      - name: Import PFX
        uses: ./repo/.github/actions/import-pfx
        with:
          PfxBase64: ${{ secrets.PfxBase64 }}
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Get Thumbprint
        id: get-thumbprint
        uses: ./repo/.github/actions/get-thumbprint
        with:
          PfxPassword: ${{ secrets.PfxPassword }}
      - name: Restore ScubaGear
        uses: actions/cache/restore@v4
        with:
          path: C:\Program Files\WindowsPowerShell\Modules\ScubaGear
          key: scubagear-directory-
      - name: Restore Dependencies
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\Documents\WindowsPowerShell\Modules
          key: powershell-directory-
      - name: Restore OPA
        uses: actions/cache/restore@v4
        with:
          path: C:\Users\runneradmin\.scubagear\Tools
          key: opa-directory-
      - name: Test
        uses: ./repo/.github/actions/test-product
        with:
          Thumbprint: ${{ steps.get-thumbprint.outputs.thumbprint }}
          Alias: Ent_Tenant6_G5
          TestParams: ${{ secrets.TestParams }}
      - name: Extract Email
        id: extract-email
        if: ${{ always() }}
        uses: ./repo/.github/actions/extract-email
        env:
          Alias: Ent_Tenant6_G5
          TestParams: ${{ secrets.TestParams }}
      - name: Notify on Failure
        if: ${{ failure() && (inputs.EmailOnFailure || inputs.GitHubEventSchedule || inputs.GitHubEventName == 'push') }}
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.NotifierUsername }}
          password: ${{ secrets.NotifierPassword }}
          subject: Nightly functional test failure
          body: The Ent_Tenant6_G5 test failed.  Please look at the "Nightly Product Functional Tests" workflow for more details.
          to: ${{ steps.extract-email.outputs.emails }}
          from: ScubaGear Notifier
