name: Run PowerShell Tests
on:
  # Run tests on each commit, newly opened/reopened PR, and
  # PR review submission (e.g. approval)
  workflow_dispatch:
  push:
    paths:
      - "**.ps1"
      - "**.psm1"
  pull_request:
    types: [opened, reopened]
    branches:
      - "main"
      - "*TestAction"
    paths:
      - "**.ps1"
      - "**.psm1"
  pull_request_review:
    types: [submitted]

jobs:
  Run-PowerShell-Tests:
    runs-on: windows-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3

    - name: Run Pester Tests
      shell: powershell
      run: |
        # Remove module from image until SCUBA steps up to 2.0+
        Get-InstalledModule -Name Microsoft.Graph.Authentication | Uninstall-Module
        ./SetUp.ps1
        Invoke-Pester -Output 'Detailed' -Path './Testing/Unit/PowerShell'