# Purpose: Run the linter against YAML files

name: Lint Check for YAML

# Run whenever YAML files are checked in
on:
  push:
    # paths:
    #   - "**.yml"
    #   - "**.yaml"
  workflow_call:
    paths:
      - "**.yml"
      - "**.yaml"
  workflow_dispatch:

jobs:
  yaml-lint-check:
    name: MegaLint YAML Check
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Setup Config File
        run: cp Testing/Linting/MegaLinter/.mega-linter-yaml.yml .mega-linter.yml
      - name: Setup Lint File
        run: cp Testing/Linting/MegaLinter/.yamllint.yml .yamllint.yml
      - name: Lint YAML
        uses: oxsecurity/megalinter/flavors/ci_light@latest
